config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: [:show] do
    resources :comments, only: :create
  end
  resources :likes, only: [:destroy, :create]

  resources :groups, only: [:new, :create, :show] do
    resources :books, only: [:index, :show, :new, :create]
    resources :movies, only: [:index, :show, :new, :create]
    resources :games, only: [:index, :show, :new, :create]
    resources :series, only: [:index, :show, :new, :create]
    resources :podcasts, only: [:index, :show, :new, :create]
    resources :members, only: [:new, :create]
  end
  resources :users, only: [:edit, :update]

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for "User", at: "auth",
        controllers: {
          sessions: 'api/v1/devise_token_auth/sessions'
        }
      resources :podcasts, only: :index
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :books
  has_many :movies
  has_many :games
  has_many :series
  has_many :podcasts

  has_many :memberships, inverse_of: :group
  has_many :members, through: :memberships, source: :user

  accepts_nested_attributes_for :memberships

  mount_uploader :image, ImageUploader

  validates :name, :image, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      current_user.add_to(@group)
      redirect_to group_path(@group), notice: "Bien créé !"
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/views/groups/_book.html.erb
<div class="book-details">
  <div class="card-product">
    <a class="book-link" data-toggle="collapse" href="#bookDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="bookDetailsCollapse<%= index %>">
      <% unless book.image_link.blank? %>
        <%= cl_image_tag book.cover, crop: :fill, height: 68, width: 68 %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
      <% end %>
      <div class="card-product-infos">
        <h2><%= book.title %></h2>
        <p><%= book.authors %></p>
        <p><small>Recommandé par <%= book.user.first_name.capitalize %></small></p>
      </div>
    </a>
    <div class="card-product-right">
      <%= render 'like', resource: book %>
    </div>
  </div>
</div>

<div class="collapse book-description" id="bookDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <% if book.owner_comment.present? || book.owner_grade.present? %>
          <div>
            <p><strong><%= book.user.first_name %> dit :</strong></p>
            <%= display_stars(book.owner_grade).html_safe %>
            <p><%= book.owner_comment %></p>
          </div>
          <br>
        <% end %>
        <h2><%= book.published_date[0, 4] if book.published_date %></h2>
        <p><strong>Genres :</strong> <%= book.genres&.join(', ') %> </p>
        <p><strong>Résumé</strong></p>
        <p><%= book.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/_game.html.erb
<div class="book-details">
  <div class="card-product">
    <a class="book-link" data-toggle="collapse" href="#gameDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="gameDetailsCollapse<%= index %>">
      <% if game.background_image %>
        <%= cl_image_tag game.background_image, crop: :fill, height: 80, width: 120; %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
      <% end %>
      <div class="card-product-infos">
        <h2><%= game.name %></h2>
        <p><%= game.released %></p>
        <p><small>Recommandé par <%= game.user.first_name.capitalize %></small></p>
      </div>
    </a>
    <div class="card-product-right">
      <div class="card-product-right">
        <%= render 'like', resource: game %>
      </div>
    </div>
  </div>
</div>

<div class="collapse book-description" id="gameDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <% if game.owner_comment.present? || game.owner_grade.present? %>
          <div>
            <p><strong><%= game.user.first_name %> dit :</strong></p>
            <%= display_stars(game.owner_grade).html_safe %>
            <p><%= game.owner_comment %></p>
          </div>
          <br>
        <% end %>
        <p><strong>Devs :</strong> <%= game.devs.join(", ") %></p>
        <p><strong>Plateformes :</strong> <%= game.platforms.join(", ") %></p>
        <p><strong>Genres :</strong> <%= game.genres.join(", ") %></p>
        <br>
        <h2>Description</h2>
        <p><%= game.description.html_safe %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/_like.html.erb
<% if current_user.likes?(resource) %>
  <%= link_to like_path(Like.find_by(user: current_user, likable: resource)), method: :delete do %>
    <i class="fas fa-heart blue"></i>
    <p><%= resource.likes.count %></p>
  <% end %>
<% else %>
  <%= link_to likes_path(resource_id: resource.id, type: resource.class), method: :post do %>
    <i class="far fa-heart"></i>
    <p><%= resource.likes_count %></p>
  <% end %>
<% end %>

app/views/groups/_movie.html.erb
<div class="book-details">
  <div class="card-product">
    <a class="book-link" data-toggle="collapse" href="#movieDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="movieDetailsCollapse<%= index %>">
      <% if movie.poster_path %>
        <%= cl_image_tag movie.poster, crop: :fill, height: 80 %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
      <% end %>
      <div class="card-product-infos">
        <h2><%= movie.title %></h2>
        <p><%= movie.release_date %></p>
        <p><small>Recommandé par <%= movie.user.first_name.capitalize %></small></p>
      </div>
      <div class="card-product-right">
        <%= render 'like', resource: movie %>
      </div>
    </a>
  </div>
</div>
<div class="collapse book-description" id="movieDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <% if movie.owner_comment.present? || movie.owner_grade.present? %>
          <div>
            <p><strong><%= movie.user.first_name %> dit :</strong></p>
            <%= display_stars(movie.owner_grade).html_safe %>
            <p><%= movie.owner_comment %></p>
          </div>
          <br>
        <% end %>

        <p><strong>Sortie :</strong> <%= movie.release_date[0, 4] if movie.release_date %></p>
        <p><strong>Genre :</strong> <%= movie.genres.join(', ') %></p>
        <p><strong>Imdb :</strong> <a href="<%= movie.imdb_url %>"><%= movie.imdb_url %></a> </p>

        <br>
        <p><strong>Résumé</strong></p>
        <p><%= movie.overview %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/_series.html.erb
<div class="book-details">
  <div class="card-product">
    <a class="book-link" data-toggle="collapse" href="#seriesDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="seriesDetailsCollapse<%= index %>">
      <% if series.poster_path %>
        <%= cl_image_tag series.poster, crop: :fill, height: 80 %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
      <% end %>
      <div class="card-product-infos">
        <h2><%= series.title %></h2>
        <p><%= series.release_date %></p>
        <p><small>Recommandé par <%= series.user.first_name.capitalize %></small></p>
      </div>
      <div class="card-product-right">
        <%= render 'like', resource: series %>
      </div>
    </a>
  </div>
</div>
<div class="collapse book-description" id="seriesDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <% if series.owner_comment.present? || series.owner_grade.present? %>
          <div>
            <p><strong><%= series.user.first_name %> dit :</strong></p>
            <%= display_stars(series.owner_grade).html_safe %>
            <p><%= series.owner_comment %></p>
          </div>
          <br>
        <% end %>

        <p><strong>Sortie :</strong> <%= series.release_date[0, 4] if series.release_date %></p>
        <p><strong>Genre :</strong> <%= series.genres.join(', ') %></p>

        <p><strong>Résumé</strong></p>
        <p><%= series.overview %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% content_for :action do %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-arrow-left fa-lg"></i>
  <% end %>
<% end %>
<% content_for :title do %>
  Nouveau groupe
<% end %>

<div class="container">
  <h3 class="text-center">Nouveau groupe</h3>
  <%= simple_form_for @group do |f| %>
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <br>
    <%= f.submit 'Créer', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/groups/show.html.erb
<% content_for :action do %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-arrow-left fa-lg"></i>
  <% end %>
<% end %>
<% content_for :title do %>
  <a data-toggle="collapse" href="#groupDetailsCollapse" role="button" aria-expanded="false" aria-controls="groupDetailsCollapse">
    <%= cl_image_tag (@group.image), crop: :fill, width: 40, height: 40, class: "avatar" %>
    <%= @group.name %>
  </a>
<% end %>

<div class="collapse" id="groupDetailsCollapse">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <%= link_to new_group_member_path(@group) do %>
          <%= icon("fas", "user-plus") %>
          Ajouter un membre
        <% end %>
        <div class="card-group-members">
          <% @group.members.each do |member| %>
            <div class="card-group-member">
              <%= cl_image_tag member.avatar, class: "avatar" %>
              <p><%= member.first_name %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs group-navs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:previous] == 'book' || params[:previous].nil? %>" id="book-tab" data-toggle="tab" href="#books" role="tab" aria-controls="book" aria-selected="false"><i class="fas fa-book"></i></a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:previous] == 'movie' %>" id="movie-tab" data-toggle="tab" href="#movies" role="tab" aria-controls="movie" aria-selected="true"><i class="fas fa-film"></i></a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:previous] == 'series' %>" id="serie-tab" data-toggle="tab" href="#series" role="tab" aria-controls="serie" aria-selected="false"><i class="fas fa-tv"></i></i></a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:previous] == 'game' %>" id="game-tab" data-toggle="tab" href="#games" role="tab" aria-controls="game" aria-selected="false"><i class="fas fa-gamepad"></i></a>
  </li>
</ul>


<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade <%= 'show active' if params[:previous] == 'book' || params[:previous].nil? %>" id="books" role="tabpanel" aria-labelledby="book-tab">
    <% if @books.any? %>
      <%= form_tag "/groups/#{@group.id}", method: :get do %>
        <div class="filter-input">
          Filtrer par genre : <%= select_tag :book_genre, options_for_select(Book::GENRES, params[:book_genre]), :onchange => "this.form.submit();" %>
        </div>
        <%= hidden_field_tag :previous, "book" %>
      <% end %>
      <%@books.each_with_index do |book, index| %>
        <%= render 'book', book: book, index: index %>
      <% end %>
    <% else %>
      <p>Aucun livre pour le moment... Ajoutes-en !</p>
    <% end %>
  </div>
  <div class="tab-pane fade <%= 'show active' if params[:previous] == 'movie' %>" id="movies" role="tabpanel" aria-labelledby="movie-tab">
    <% if @movies.any? %>
      <%= form_tag "/groups/#{@group.id}", method: :get do %>
        Filtrer par genre : <%= select_tag :movie_genre, options_for_select(Movie::GENRES, params[:movie_genre]), :onchange => "this.form.submit();" %>
        <%= hidden_field_tag :previous, "movie" %>
      <% end %>
      <%@movies.each_with_index do |movie, index| %>
        <%= render 'movie', movie: movie, index: index %>
      <% end %>
    <% else %>
      <p>Aucun film pour le moment... Ajoutes-en !</p>
    <% end %>
  </div>
  <div class="tab-pane fade <%= 'show active' if params[:previous] == 'series' %>" id="series" role="tabpanel" aria-labelledby="serie-tab">
    <% if @series.any? %>
      <%= form_tag "/groups/#{@group.id}", method: :get do %>
        Filtrer par genre : <%= select_tag :series_genre, options_for_select(Series::GENRES, params[:series_genre]), :onchange => "this.form.submit();" %>
        <%= hidden_field_tag :previous, "series" %>
      <% end %>
      <%@series.each_with_index do |series, index| %>
        <%= render 'series', series: series, index: index %>
      <% end %>
    <% else %>
      <p>Aucune série pour le moment... Ajoutes-en !</p>
    <% end %>
  </div>
  <div class="tab-pane fade <%= 'show active' if params[:previous] == 'game' %>" id="games" role="tabpanel" aria-labelledby="game-tab">
    <% if @games.any? %>
      <%= form_tag "/groups/#{@group.id}", method: :get do %>
        Filtrer par genre : <%= select_tag :game_genre, options_for_select(Game::GENRES, params[:game_genre]), :onchange => "this.form.submit();" %>
        <%= hidden_field_tag :previous, "game" %>
      <% end %>
      <%@games.each_with_index do |game, index| %>
        <%= render 'game', game: game, index: index %>
      <% end %>
    <% else %>
      <p>Aucun jeu pour le moment... Ajoutes-en !</p>
    <% end %>
  </div>
</div>

<div class="book-actions dropup">
  <a class="btn btn-add" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-plus fa-3x btn-white"></i>
  </a>
  <div class="dropdown-menu menu-narrow">
    <div class="add-menu">
      <%= link_to new_group_book_path(@group) do %>
        <i class="fas fa-book"></i>
        <p>Livre</p>
      <% end %>
      <%= link_to new_group_movie_path(@group) do %>
        <i class="fas fa-film"></i>
        <p>Film</p>
      <% end %>
      <%= link_to new_group_series_path(@group) do %>
        <i class="fas fa-tv"></i>
        <p>Série</p>
      <% end %>
      <%= link_to new_group_game_path(@group) do %>
        <i class="fas fa-gamepad"></i>
        <p>Jeu</p>
      <% end %>
    </div>
  </div>
</div>