config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: [:show] do
    resources :comments, only: :create
  end
  resources :likes, only: [:destroy, :create]

  resources :groups, only: [:new, :create, :show] do
    resources :books, only: [:index, :show, :new, :create]
    resources :movies, only: [:index, :show, :new, :create]
    resources :games, only: [:index, :show, :new, :create]
    resources :series, only: [:index, :show, :new, :create]
    resources :podcasts, only: [:index, :show, :new, :create]
    resources :members, only: [:new, :create]
  end
  resources :users, only: [:edit, :update]

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for "User", at: "auth",
        controllers: {
          sessions: 'api/v1/devise_token_auth/sessions'
        }
      resources :podcasts, only: :index
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_like.html.erb
<% if current_user.likes?(resource) %>
  <%= link_to like_path(Like.find_by(user: current_user, likable: resource)), method: :delete do %>
    <i class="fas fa-heart blue"></i>
    <p><%= resource.likes_count %></p>
  <% end %>
<% else %>
  <%= link_to likes_path(resource_id: resource.id, type: resource.class), method: :post do %>
    <i class="far fa-heart"></i>
    <p><%= resource.likes_count %></p>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-left">
    <%= yield :action %>
    <div class="navbar-title">
      <%= yield :title %>
    </div>
  </div>
  <div class="navbar-right">
    <%= yield :add %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="wrapper">
  <!-- Sidebar -->
  <nav id="sidebar">

    <div id="dismiss">
      <i class="fas fa-arrow-left"></i>
    </div>
    <div class="sidebar-header">
      <% if user_signed_in? %>
        <%= cl_image_tag current_user.avatar, class: "avatar-large" %>
        <p><%= current_user.first_name %></p>
      <% end %>
    </div>

    <ul class="list-unstyled components">
      <li>
        <%= link_to root_path do %>
          <%= icon("fas", "user-friends") %>
          <p>Mes groupes</p>
        <% end %>
      </li>
      <li>
        <%= link_to new_group_path do %>
          <%= icon("fas", "user-plus") %>
          <p>Nouveau groupe</p>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to edit_user_path(current_user) do %>
            <%= icon("fas", "user-edit") %>
            <p>Profil</p>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= icon("fas", "user-times") %>
            <p>Me déconnecter</p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>

  <!-- Dark Overlay element -->
  <div class="overlay"></div>
</div>

app/views/shared/_tabs.html.erb
<% content_for :action do %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-arrow-left fa-lg"></i>
  <% end %>
<% end %>
<% content_for :title do %>
  <a data-toggle="collapse" href="#groupDetailsCollapse" role="button" aria-expanded="false" aria-controls="groupDetailsCollapse">
    <%= cl_image_tag (@group.image), crop: :fill, width: 40, height: 40, class: "avatar" %>
    <p><%= @group.name %></p>
  </a>
<% end %>

<div class="collapse" id="groupDetailsCollapse">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <%= link_to new_group_member_path(@group) do %>
          <%= icon("fas", "user-plus") %>
          Ajouter un membre
        <% end %>
        <div class="card-group-members">
          <% @group.members.each do |member| %>
            <div class="card-group-member">
              <%= cl_image_tag member.avatar, class: "avatar" %>
              <p><%= member.first_name %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs group-navs">
  <li class="nav-item">
    <%= link_to group_books_path(@group), class: "nav-link #{'active' if params[:controller] == 'books'}" do %>
      <i class="fas fa-book"></i>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to group_movies_path(@group), class: "nav-link #{'active' if params[:controller] == 'movies'}" do %>
      <i class="fas fa-film"></i>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to group_series_index_path(@group), class: "nav-link #{'active' if params[:controller] == 'series'}" do %>
      <i class="fas fa-tv"></i>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to group_games_path(@group), class: "nav-link #{'active' if params[:controller] == 'games'}" do %>
      <i class="fas fa-gamepad"></i>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to group_podcasts_path(@group), class: "nav-link #{'active' if params[:controller] == 'podcasts'}" do %>
      <i class="fas fa-podcast"></i>
    <% end %>
  </li>
</ul>