config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: [:show] do
    resources :comments, only: :create
  end
  resources :likes, only: [:destroy, :create]

  resources :groups, only: [:new, :create, :show] do
    resources :books, only: [:index, :show, :new, :create]
    resources :movies, only: [:index, :show, :new, :create]
    resources :games, only: [:index, :show, :new, :create]
    resources :series, only: [:index, :show, :new, :create]
    resources :podcasts, only: [:index, :show, :new, :create]
    resources :members, only: [:new, :create]
  end
  resources :users, only: [:edit, :update]

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for "User", at: "auth",
        controllers: {
          sessions: 'api/v1/devise_token_auth/sessions'
        }
      resources :podcasts, only: :index
    end
  end
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :group
  belongs_to :user

  GENRES = []
  serialize :genres, Array

  mount_uploader :image, ImageUploader
end

app/controllers/api/v1/podcasts_controller.rb
class Api::V1::PodcastsController < Api::V1::BaseController
  def index
    @podcasts = Podcast.all
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_group, only: [:index, :new, :create]

  def index
    @podcasts = @group.podcasts.where(nil).order('likes_count DESC') # creates an anonymous scope
    @podcasts = @podcasts.filtered(params[:book_genre]).order('likes_count DESC') if params[:book_genre].present?
  end

  def new
    if params[:search].present?
      @podcasts = ListenApi.search(params[:search][:query])
    end
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)

    @podcast.user = current_user
    @podcast.group = @group

    @podcast.remote_image_url = @podcast.image_path

    if @podcast.save
      redirect_to group_podcasts_path(@group), notice: "Bien ajouté !"
    else
      render :new, alert: "Un problème est survenu..."
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def podcast_params
    permitted_params = params.require(:podcast).permit(:owner_grade, :owner_comment, :title, :description, :image_path, :genres, :publisher)
    permitted_params[:genres] = permitted_params[:genres].split(" ")
    return permitted_params
  end
end

app/views/podcasts/_podcast.html.erb
<div class="book-details">
  <div class="card-product">
    <a class="book-link" data-toggle="collapse" href="#bookDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="bookDetailsCollapse<%= index %>">
      <% if podcast.image %>
        <%= cl_image_tag podcast.image, crop: :fill, height: 68, width: 68 %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
      <% end %>
      <div class="card-product-infos">
        <h2><%= podcast.title %></h2>
        <p><%= podcast.publisher %></p>
        <p><small>Recommandé par <%= podcast.user.first_name.capitalize %></small></p>
      </div>
    </a>
    <div class="card-product-right">
      <%= render 'shared/like', resource: podcast %>
    </div>
  </div>
</div>

<div class="collapse book-description" id="bookDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <% if podcast.owner_comment.present? || podcast.owner_grade.present? %>
          <div>
            <p><strong><%= podcast.user.first_name %> dit :</strong></p>
            <%= display_stars(podcast.owner_grade).html_safe %>
            <p><%= podcast.owner_comment %></p>
          </div>
          <br>
        <% end %>
        <p><strong>Résumé</strong></p>
        <p><%= podcast.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/podcasts/_podcast_search.html.erb
<a class="book-details" data-toggle="collapse" href="#podcastDetailsCollapse<%= index %>" role="button" aria-expanded="false" aria-controls="podcastDetailsCollapse<%= index %>">
  <div class="card-product">
    <% if podcast.image %>
      <%= image_tag podcast.image %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="width: 70px;" />
    <% end %>
    <div class="card-product-infos">
      <h2><%= podcast.title %></h2>
      <p><%= podcast.publisher %></p>
    </div>
    <div class="card-product-right">
      <%= icon('fas', 'chevron-down') %>
    </div>
  </div>
</a>
<div class="collapse book-description" id="podcastDetailsCollapse<%= index %>">
  <div class="card-trip">
    <div class="card-trip-infos">
      <div>
        <%= render 'share', podcast: podcast, index: index %>
        <p><strong>Résumé</strong></p>
        <p><%= podcast.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/podcasts/_share.html.erb
<button type="button" class="btn btn-sm btn-ghost btn-share" data-toggle="modal" data-target="#resourceModal<%=index%>">
  Partager
</button>

<!-- Modal -->
<div class="modal fade" id="resourceModal<%=index%>" tabindex="-1" role="dialog" aria-labelledby="resourceModalLabel<%=index%>" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for [@group, @podcast] do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="resourceModalLabel<%=index%>">Donne ton avis gros</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.input :owner_comment, label: "Un petit commentaire ?", input_html: { class: "owner_comment_input" } %>
          <%= f.input :owner_grade, collection: (1..5).to_a, label: "Une petite note ?", input_html: { class: "starRating" } %>
          <%= f.input :title, as: :hidden, input_html: { value: podcast.title } %>
          <%= f.input :description, as: :hidden, input_html: { value: podcast.description } %>
          <%= f.input :image_path, as: :hidden, input_html: { value: podcast.image } %>
          <%= f.input :genres, as: :hidden, input_html: { value: podcast.genres } %>
          <%= f.input :publisher, as: :hidden, input_html: { value: podcast.publisher } %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
          <%= f.submit "Partager !", class: "btn btn-ghost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/podcasts/index.html.erb
<% content_for :add do %>
  <%= link_to new_group_podcast_path(@group), class: "navbar-brand" do %>
    <i class="fas fa-plus fa-lg btn-white"></i>
  <% end %>
<% end %>

<%= render 'shared/tabs' %>

<% if @podcasts.any? %>
  <%= form_tag "/groups/#{@group.id}/podcasts", method: :get do %>
    Filtrer par genre : <%= select_tag :podcast_genre, options_for_select(Podcast::GENRES, params[:podcast_genre]), :onchange => "this.form.submit();" %>
    <%= hidden_field_tag :previous, "podcast" %>
  <% end %>
  <%@podcasts.each_with_index do |podcast, index| %>
    <%= render 'podcast', podcast: podcast, index: index %>
  <% end %>
<% else %>
  <p>Aucune série pour le moment... Ajoutes-en !</p>
<% end %>

app/views/podcasts/new.html.erb
<% content_for :action do %>
  <%= link_to group_podcasts_path(@group), class: "navbar-brand" do %>
    <i class="fas fa-arrow-left fa-lg"></i>
  <% end %>
<% end %>
<% content_for :title do %>
  <%= link_to group_podcasts_path(@group) do %>
    <%= cl_image_tag (@group.image), crop: :fill, width: 40, height: 40, class: "avatar" %>
    Recommander un podcast
  <% end %>
<% end %>

<div class="container">
  <div class="book-search">
    <%= simple_form_for :search, url: new_group_podcast_path(@group), method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Chercher un podcast..." />
        <button type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i>
        </button>
      </div>
    <% end %>
  </div>

  <% if @podcasts %>
    <% if @podcasts.any? %>
      <%@podcasts.each_with_index do |podcast, index| %>
        <%= render 'podcast_search', podcast: podcast, index: index %>
      <% end %>
    <% else %>
      <p>Aucun résultat...</p>
    <% end %>
  <% else %>
    <p>Effectuez une recherche pour voir les résultats!</p>
  <% end %>
</div>